services:
  urinal-fish:
    image: ghcr.io/schembriaiden/urinal-fish-bot:latest
    container_name: urinal-fish
    restart: unless-stopped
    env_file:
      - ${ENV_FILE:-.env}
    volumes:
      - ./data:/data
